<?php

/**
 * Created by PhpStorm.
 * User: rus
 * Date: 13.07.16
 * Time: 20:34
 */
require_once 'tovar.php';

class ITtovar extends Tovar
{
    private static $countSelling;
    private $sellCopies = 0;

    public function __clone()
    {
        $this->sellCopies = 0;
        return parent::__clone(); // TODO: Change the autogenerated stub
    }

    public static function NewSelling( $numberSelling )
    {
        Self::$countSelling += $numberSelling;
    }

    public function Sell($numberSelling)
    {
        $this->sellCopies += $numberSelling;
        self::NewSelling($numberSelling);
    }
    /**
     * @return mixed
     */
    public static function getCountSelling()
    {
        return self::$countSelling;
    }

    /**
     * @return int
     */
    public function getSellCopies()
    {
        return $this->sellCopies;
    }
}